### ISSUE TITLE
Jekyll serve error sass

### ISSUE THREAD

**Issue by giuseppefrattura** [biomadeira/jasper#1]
Hi,
i've just clone the repository but when i try to run "jekyll serve" i have this error:

"Conversion error: Jekyll::Converters::Scss encountered an error while converting 'jasper/assets/css/main.scss':
                    File to import not found or unreadable: syntax. on line 8"

I use Jekyll v 3.0.

Thanks

**Comment by biomadeira** [comment]
@giuseppefrattura Hi there,

 I'm on Mac OS and just updated my ruby and jeykll versions to 2.2.9 and 3.0.0, respectively. It seems to be working fine here, apart from some deprecation warnings in the jekyll_rssgenerator gem.

I have noticed that the Ghost's theme has new features, such as toggleable sliding sidebar on the right side... I am upgrading the theme now, and you might try later again with the new version. Hopefully it will 'resolve' the problem :)

In the meantime try adding the line below to your _config.yml:

```
exclude: [vendor]
```

Just committed these fixes: https://github.com/biomadeira/jasper/commit/42688dbe97a546a5ac016fc45c0220a364ec5a2a

**Comment by biomadeira** [comment]
@giuseppefrattura Just updated the theme! Check it up at https://biomadeira.github.io/jasper/ and fork the new version https://github.com/biomadeira/jasper/tree/master

Doesn't rely on any sass and should work for you. Let me know if that is the case :+1:
