### ISSUE TITLE
Post expert fetching technique in the Post List page

### ISSUE THREAD

**Issue by fareez-ahamed** [biomadeira/jasper#11]
Hi

Thanks for this amazing work!!

Came across a bug, If I'm having a bold or italic text in the article and if its cut in the middle while displaying the post list, the style affects the entire page

![screenshot from 2016-01-03 14 05 44](https://cloud.githubusercontent.com/assets/2500740/12077959/243a5d14-b223-11e5-896b-98c3927f6b46.png)

**Comment by biomadeira** [comment]
@fareez-ahamed thanks for reporting this.

This commit https://github.com/biomadeira/jasper/commit/0cfee9584c176e1454daf96fab90c3cf818e9660 should fix the problem ;)
