### ISSUE TITLE
About page returns a 404 error

### ISSUE THREAD

**Issue by KshitijKarthick** [biomadeira/jasper#14]
##### Problem

The url requested is http://0.0.0.0:4000/jasper/about
Accessed via the right menu , about link
##### Steps
- git clone https://github.com/biomadeira/jasper.git
- cd jasper
- jekyll serve

**Comment by biomadeira** [comment]
Hi @KshitijKarthick,

That's weird. Have you tried adding **.html** to the link just to see if it works?
http://0.0.0.0:4000/jasper/about.html

Both the live version and my 'local' work fine. Could you past the error log you get when doing 
`jekyll serve -t` and trying to access the page?

**Comment by KshitijKarthick** [comment]
- Appending the .html to the link returns the required page.
  But the side menu leads to */about and not */about.html
- Upon execution with `jekyll serve -t` , no errors thrown upon a 404 page

**Comment by biomadeira** [comment]
Hi @KshitijKarthick,

This fix https://github.com/biomadeira/jasper/pull/19 should definitely put it to work...

Thanks

**Comment by KshitijKarthick** [comment]
Thanks @biomadeira ,
Amazing work gone into this though :+1:
