### ISSUE TITLE
Missing characters in typographic ligatures "fi" -> "i"

### ISSUE THREAD

**Issue by gully** [biomadeira/jasper#18]
Hi there,
The Jekyll theme has been working great, thanks again for putting it together.

One strange thing I noticed today-- all of the instances of the two-letter sequence "fi" were replaced with "i", in the content of my blog posts.  It's definitely something about the font because the developer tools shows the original "fi" content.  It's a problem with the _ligature_ for blended _fi_ typography.  I'm not quite sure how to go about fixing it, other than trying to change the font.  Has anyone else experienced this?  It's conceivable I screwed something up while mucking around with the multiple author support experiments, so forgive me if this is my own problem.  I've replicated the behavior on several different browsers and devices, and I see it serving both locally and remote.
I'll report back about what I find out.

**Comment by gully** [comment]
<img width="359" alt="screen shot 2016-01-24 at 2 01 17 pm" src="https://cloud.githubusercontent.com/assets/860227/12534807/6ae589c8-c2a4-11e5-8f9e-c41797c67ad8.png">

**Comment by JohnONolan** [comment]
https://github.com/google/fonts/issues/8

**Comment by davelab6** [comment]
The update to Merriweather was made in advance of the Firefox 44 launch on Tuesday that will mean the old files will just stop working. 

The bug with fi/fl ligatures has a workaround - you can turn ligatures off with CSS to work around this until then:

```
-webkit-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
-moz-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
-o-font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
font-feature-settings: 'liga' 0, 'onum' 1, 'kern' 1;
```

**Comment by gully** [comment]
Thank you all, it looks like this affected a lot of pages out there.

**Comment by biomadeira** [comment]
Great help guys @JohnONolan @davelab6  and @gully!

I had no idea about this one...

Cheers

**Comment by rphuber** [comment]
You could also get the font from fontsquirrel for free and host it yourself.  It is more up to date than the one hosted on google.  That worked to fix the issue for me.

**Comment by davelab6** [comment]
@rphuber if you do that, the italics will stop working tomorrow for Firefox 44 users (which you can test today with Firefox Developer Edition)

**Comment by davelab6** [comment]
The fix was pushed to the Google Fonts API, so you should be able to confirm and close this now

**Comment by biomadeira** [comment]
Thank you all guys! The problem has been resolved so all good ;)
