### ISSUE TITLE
Quoting the fisherman and the bussiness man

### ISSUE THREAD

**Issue by oz123** [biomadeira/jasper#22]
Hi, 
I noticed all your example posts have an exact author except that one. You can add the original author two. 
This is a story which originally was written by Heinrich Böll, and had such success it eventually became the one you have in your examples. The original German version is called ''[Anekdote zur Senkung der Arbeitsmoral](https://en.wikipedia.org/wiki/Anekdote_zur_Senkung_der_Arbeitsmoral)", you can find the credits in the link.

**Comment by biomadeira** [comment]
Thanks @oz123 

Sorry for the ignorance... I will add it shortly ;)
