### ISSUE TITLE
'redcarpet' Markdown engine, not be supported on GitHub Pages after May 1st.

### ISSUE THREAD

**Issue by ashishapy** [biomadeira/jasper#23]
I liked this theme and tried to deploy on Github pages, but I get below email from GitHub.

```
The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. 
At that time, your site will use 'kramdown' for markdown rendering instead. 
To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. 
For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
```

How to get correct version on github pages?

**Comment by hungdh9x** [comment]
@ashishapy change setting in `_config.yml` as below: 

```
# Jykell configuration
markdown: kramdown
highlighter: rouge
```

**Comment by biomadeira** [comment]
That's good to know! Thanks @ashishapy and @hungdh0x5e

**Comment by biomadeira** [comment]
Just pushed a couple of commits to address this https://github.com/biomadeira/jasper/commit/c0442be90cb4185cc3f19f7c7199e7bb061f8130 and https://github.com/biomadeira/jasper/commit/7632ba7d82fecbb5f06e65f38a5bc3533570bde6
