### ISSUE TITLE
disqus doesn't work on post

### ISSUE THREAD

**Issue by ashishapy** [biomadeira/jasper#24]
disqus is't working on post. Not even demo site as well.

Regards
Ashish

**Comment by mostafahussein** [comment]
Hello ahishapy,

I made it work by adding the following to an md/html file from `_posts` folder.
just open the file and add it under `layout: post`

```
disqus: true
```

but i don't know how to enable it globally as modifying _layouts/post didn't work. also dont forget to register your website on disqus.com and update _config.yml with your shortname, finally run `jekyll build` then `jekyll serve`

Note: you will need to add `disqus: true` for each post where you need to make disqus comments available

**Comment by mostafahussein** [comment]
@ashishapy if your issue solved you should close this one

**Comment by ashishapy** [comment]
@mostafahussein Thank you. Yes that helped me.
I made one more change in "disqus.html" file
`dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';`
to 
`dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';`

to get it work on https site.

**Comment by biomadeira** [comment]
Great stuff @mostafahussein and @ashishapy 

Thanks!
