### ISSUE TITLE
Do links in the navigation bar get automatically generated?

### ISSUE THREAD

**Issue by Daniel-Wang** [biomadeira/jasper#31]

**Comment by Daniel-Wang** [comment]
Also, running locally, my about and author pages are fine, but online my about page doesn't take up the whole page and my author page is not found?

**Comment by biomadeira** [comment]
Hi @Daniel-Wang,

They are kind of a mix between automatic and manual. You can find/edit them [here](https://github.com/biomadeira/jasper/blob/master/_includes/navigation.html)

Cheers!
