### ISSUE TITLE
code block syntax highlighting

### ISSUE THREAD

**Issue by baurigae** [biomadeira/jasper#4]
Very nice port, thanks for sharing it.
I was wondering if the lack of syntax highlighting in code blocks is by design, or accidental?

**Comment by biomadeira** [comment]
@baurigae Thanks! Code highlighting was something I knew was not working properly... anyways just pushed a fix https://github.com/biomadeira/jasper/commit/4fed0b629cebf4cc0e3a87022f4094d88c8b00cd 

If you see this [post](http://biomadeira.github.io/jasper/a-full-and-comprehensive-style-test/#code) the snipped below is now highlighted as expected ;)

```
{% highlight css %}
#container {
    float: left;
    margin: 0 -240px 0 0;
    width: 100%;
}
{% endhighlight %}
```

Cheers

**Comment by baurigae** [comment]
Super, thanks!

**Comment by hungdh9x** [comment]
@biomadeira Can I using `highlight.js` in theme as  below

![](http://pik.vn/2016bab341bd-1516-43c6-bfdb-2a168d074c19.png)

**Comment by biomadeira** [comment]
@hungdh0x5e I guess you can use https://highlightjs.org/. They seem to have great coverage of languages and very neat styles... in any case code highlighting works already fine with the highlight tag as below

```
{% highlight javascript %}
// some code
{% endhighlight %}
```

Would you want me to support highlight.js in jasper?

**Comment by hungdh9x** [comment]
@biomadeira Yes, that is exactly what i want. With highlight tag of theme, i like display code in box with scroll than display full code, and more color :)

**Comment by biomadeira** [comment]
@hungdh0x5e Sounds cool! I can add that later tonight. I will get back to you!

**Comment by hungdh9x** [comment]
Yeah, wait you :D

**Comment by biomadeira** [comment]
@hungdh0x5e Just added it here https://github.com/biomadeira/jasper/commit/4ec58d643b7c0b150dbd11df383a06f0de9ff9f9

To change the style just edit the link in [default.html](https://github.com/biomadeira/jasper/blob/master/_layouts/default.html#l24) from //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/default.min.css

to http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/monokai.min.css 

in the example of using monokai as the main style.

Should just work!
