### ISSUE TITLE
_config.yml spelling error?

### ISSUE THREAD

**Issue by thatrobotdev** [biomadeira/jasper#54]
Hello! I think I might've found a spelling error of Jekyll in `_config.yml`, but I'm not sure if it is intended.

To fix it, change the first line from

 `# Jykell configuration`

to

`# Jekyll configuration`

**Comment by biomadeira** [comment]
Fixed https://github.com/jekyller/jasper/commit/85957a9b5907dcf5d2cb1ea5f0166a4b50f600e1
