### ISSUE TITLE
slash after repository name in all post links

### ISSUE THREAD

**Issue by egiathamaershada** [biomadeira/jasper#8]
just like the title said
there is another slash '/' after repository name in all post links

example in your page
<code>http://biomadeira.github.io/jasper//i-have-a-dream</code>

it isn't something big since everything works great so far
i use this theme now because i love ghost and jekyll

**Comment by biomadeira** [comment]
Hi @egiathamaershada 

Thanks for reporting! This should fix it https://github.com/biomadeira/jasper/commit/387456f8bb8472a4160c93bb4be59ef533786be4

Cheers
